GET http://localhost:3001/api/expensiveControls/byUser
Content-Type: application/json
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpZCI6IjYxMzA5Y2E5YTE3M2Y4MzhlMWMwZTZlMCIsImVtYWlsIjoiZnJhbmNpc2NvLm5vcnRlc0BnbWFpbC5jb20iLCJpYXQiOjE2MzA2NjI5OTMsImV4cCI6MTYzMTI2Nzc5M30.AWk_qDhy5yJ1HoJh1jarhtTzSdISpZcNRvNxy_cBVyw