GET http://localhost:3001/api/expensiveControls/byUser
Content-Type: application/json
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpZCI6IjYxMzczNTUzZDA2NTgyMzQ4OTExOTI5NyIsImVtYWlsIjoidGVzdEBnbWFpbC5jb20iLCJpYXQiOjE2MzEwMDgwODMsImV4cCI6MTYzMTYxMjg4M30.isELV-Jhi5zghOkYJeZCdutDtDaQx-zXJDzHwIZzkZ4