POST http://localhost:3001/api/users/login
Content-Type: application/json

{
  "email": "francisco.nortes@gmail.com",
  "password": "Fn485517"
}

### 
POST https://expensive-control-app.herokuapp.com/api/users/login
Content-Type: application/json

{
  "email": "francisco.nortes@gmail.com",
  "password": "Fn485517"
}